### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bdgenomics/utils/misc/HadoopUtil

### ISSUE THREAD

**Issue by LeonisX** [bigdatagenomics/utils#68]
I ran these code (https://github.com/FusionWorks/jbrowse-adam), run by SBT

scala> AdamConverter.vcfToADAM("file:///home/leonis/jbrowse-adam-alldata/biodtfs/dbsnp_b37_20.vcf", "file:///home/leonis/dbsnp_b37_20.vcf.adam")

and received this error:

java.lang.NoClassDefFoundError: org/bdgenomics/utils/misc/HadoopUtil$
  at org.bdgenomics.adam.rdd.ADAMContext.loadVcf(ADAMContext.scala:584)
  at md.fusionworks.adam.jbrowse.tools.AdamConverter$.vcfToADAM(AdamConverter.scala:27)
  ... 43 elided
Caused by: java.lang.ClassNotFoundException: org.bdgenomics.utils.misc.HadoopUtil$
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 45 more

Problem - broken (empty, don't have class files) library bdg-utils-misc (http://mvnrepository.com/artifact/org.bdgenomics.bdg-utils/bdg-utils-misc)

For now I decide this so:
compile bigdatagenomics/utils and manually add utils-misc_2.11-0.2.5-SNAPSHOT.jar to lib/

Please, fix libraries bdg-utils-misc at Maven repository, or publish new version

**Comment by LeonisX** [comment]
Found at MavenCentral correct artefact:
http://mvnrepository.com/artifact/org.bdgenomics.utils/utils-misc_2.10/0.2.4
Please, close issue.

**Comment by fnothaft** [comment]
Sorry for the slow reply—thanks for confirming that you were able to find a correct artifact. I'll close this.
